name: Release
on: 
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'     
        required: true
        default: 'release'
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: adoptopenjdk:16-jdk
      options: --user root
    steps:
      - run: apt update && apt install git -y
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v1
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew checkVersion build publish curseforge github --stacktrace
        env:
          RELEASE_CHANNEL: ${{ github.event.inputs.channel }}
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/